### PR TITLE
Renamed the tempo quarter micro seconds duration to its proper name.

### PR DESCRIPTION
**Pull request by stephaneeybert**

### CODE REVIEW

**Comment by chrisguttandin** [comment]
Thanks for the PR. Could you please also rename the property in the implementation and the test fixtures?

https://github.com/chrisguttandin/midi-json-parser-worker/search?q=microsecondsPerBeat&unscoped_q=microsecondsPerBeat

**Comment by stephaneeybert** [comment]
No trouble.

**Comment by chrisguttandin** [comment]
Thanks. Unfortunately there are some more fixtures which contain this event. I'm not sure why they did not show up in the GitHub search.

```txt
test/fixtures/98137.json
test/fixtures/TheEntertainer.json
test/fixtures/because.json
test/fixtures/californication.json
test/fixtures/minute_waltz.json
test/fixtures/rachmaninov3.json
test/fixtures/test.json
```

Could you please change those as well?

**Comment by stephaneeybert** [comment]
Hope I haven't missed any !

**Pull request merged**
